# Generated by Django 5.0.1 on 2024-02-07 08:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='token_id',
            field=models.CharField(default=uuid.uuid4, max_length=256, unique=True),
        ),
    ]
