# Generated by Django 5.0.1 on 2024-05-06 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    def insert_skill(apps, schema_editor):
        Skill = apps.get_model("myapp", "Skill")
        Skill.objects.bulk_create(
            [
                Skill(skill_name="java", skill_type=1, display_order=1),
                Skill(skill_name="python", skill_type=1, display_order=2),
                Skill(skill_name="javaScript", skill_type=1, display_order=3),
                Skill(skill_name="kotlin", skill_type=1, display_order=4),
                Skill(skill_name="SpringBoot", skill_type=2, display_order=1),
                Skill(skill_name="Django", skill_type=2, display_order=2),
                Skill(skill_name="vue.js", skill_type=2, display_order=3),
            ]
        )

    dependencies = [
        ("myapp", "0002_alter_employee_token_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "skill_id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("skill_name", models.CharField()),
                ("skill_type", models.IntegerField(blank=True, null=True)),
                ("display_order", models.IntegerField()),
            ],
            options={
                "db_table": "skill",
            },
        ),
        migrations.AddField(
            model_name="employee",
            name="testhoge",
            field=models.IntegerField(choices=[(0, "Zero"), (1, "One")], null=True),
        ),
        migrations.CreateModel(
            name="EmployeeSkill",
            fields=[
                (
                    "employee_skill_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.employee"
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="myapp.skill"
                    ),
                ),
            ],
            options={
                "db_table": "employee_skill",
            },
        ),
        migrations.RunPython(insert_skill),
    ]
