# Generated by Django 5.0.1 on 2024-01-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_employee_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
