version: '3'

services:
  postgres_db:
    image: postgres:latest
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=django_sample
    volumes:
      - db-store:/var/lib/postgressql/data
volumes:
  db-store: